### ISSUE TITLE
Limit login access to members of FACN1

### ISSUE THREAD

**Issue by philawsophizing** [FACN1/Lario#17]
1. User goes to login page: "If you are a member of the facn1 organization enter github handle and click here to login"
2. Check github endpoint if they are a member of facn1
3. If not a member redirect to view saying "must be a member of facn1 to access kittyio"
4. If a member, carry on flow to get token, set cookie.

**Comment by Karyum** [comment]
we can do this using this: https://developer.github.com/v3/orgs/

GET /orgs/:org

**Comment by Karyum** [comment]
done in #20
