### ISSUE TITLE
Easier way to check for the FACN1 organisation

### ISSUE THREAD

**Issue by jwld** [FACN1/Lario#36]
https://github.com/FACN1/Lario/blob/master/src/routes/temp.js#L53-L61

You could instead do:
```js
if (parsedOrgBody[0].login !== 'FACN1') { 
  return reply.redirect('/');
}
```

It's a bit confusing since `typeof parsedOrgBody` says it's an object, but it seems to be an array with one property. Not sure what's going on there!

**Comment by JWLD** [comment]
Also see #32 - it would save you some of this pain!

**Comment by jwld** [comment]
Oh waaaait, I see what you're doing, carry on!
