### ISSUE TITLE
Counter in temp.js

### ISSUE THREAD

**Issue by emilyb7** [FACN1/Lario#38]
Why rely on a counter? Surely users can only be a member of FACN1 once.

You should stop iterating over the array of organisations as soon as you find one organisation where the login === facn1.

Hint: map may not be the right way of doing this ;)

**Comment by emilyb7** [comment]
nice :) could also use `.some`as you only need to return a boolean value!

**Comment by philawsophizing** [comment]
Didn't know about .some.. that would be better :)

On Apr 13, 2017, at 3:03 PM, Emily Bertwistle <notifications@github.com<mailto:notifications@github.com>> wrote:


nice :) could also use .someas you only need to return a boolean value!
